### ISSUE TITLE
skimage.external does not exist in newer packages

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#1]
Hi Mika,

I get the following error, which seems to affect suite2p and is caused by the fact that **tifffile** is now on its own; hence, skimage.external doesn't exist any more. (See https://github.com/MouseLand/suite2p/issues/324)

`Traceback (most recent call last):
  File "processVideos.py", line 37, in <module>
    voluseg.step1_process_images(parameters)
  File "/groups/ahrens/home/howj/.local/lib/python3.6/site-packages/voluseg/_steps/step1.py", line 10, in process_images
    from skimage.external import tifffile
ModuleNotFoundError: No module named 'skimage.external'`

Thanks,
Javier

**Comment by mikarubi** [comment]
Hi Javier,

Thanks for the feedback.
Just to double check, you can `import tifffile` directly, is this correct?

Best regards,
Mika

**Comment by javierhow** [comment]
Yes, directly importing works well.

Thanks!
Javier

**Comment by mikarubi** [comment]
Ok sounds good, I just updated the code.
Try to pull again and let me know if it works now.

**Comment by javierhow** [comment]
It works! Thank you
- Javier
