### ISSUE TITLE
Download link for sample data

### ISSUE THREAD

**Issue by luiztauffer** [mikarubi/voluseg#15]
@mikarubi could you provide a link that allows for programmatic downloading of the sample data? 
The one provided on README.md only works for doing this manually through the browser. One solution could be zipping all the content as just one zip file, and making it available

**Comment by mikarubi** [comment]
here is a link to google drive, i believe it should be possible to amend it to download programmatically (e.g. with wget):
https://drive.google.com/file/d/1d_D_OAPIwUIzBFCghrBbDOMMLIaeHlQB/view?usp=sharing
