### ISSUE TITLE
Change file storage of parameters form pickle to JSON

### ISSUE THREAD

**Issue by luiztauffer** [mikarubi/voluseg#18]
I suggest that, if necessary to store parameters as file, that we change from pickle to JSON.
JSON is a more suitable format to store parameters and metadata in general:
- it is readable by human users
- readable by other technologies, such as javascript
- it is the standard for for transferring data over the network, e.g. rest apis
- allows for easy validation

**Comment by mikarubi** [comment]
Yes, agree.
* We should double check if the all current parameters contents can be stored as JSON.
* We should also keep the pickle read/write mechanisms for backwards compatibility.
