### ISSUE TITLE
Division of integers produces floats

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#2]
Hi Mika,

Sorry to keep being difficult. I'm running Python 3, which makes integer division produce floats. Hence, I'm getting this error:
`org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/groups/ahrens/home/howj/.local/lib/python3.6/site-packages/voluseg/_ste                                    ps/step1.py", line 89, in initial_processing
    volume_input = volume_input[:, :ly, :]
TypeError: slice indices must be integers or None or have an __index__ method`

ly should be an int, since I am dividing 2048 by 2, but for Python 3 it produces floats. (https://stackoverflow.com/questions/21316968/division-in-python-2-7-and-3-3)

Best,
Javier

**Comment by mikarubi** [comment]
Hi Javier,
No problems, thanks for picking these up. Try to pull again and see if it works.
Also, let me know if you need help with choosing parameter settings, etc.
Mika

**Comment by javierhow** [comment]
Lovely! Thank you. And yes, I think I'll email you (kinda) offline.
