### ISSUE TITLE
Warning in Step 4

### ISSUE THREAD

**Issue by javierhow** [mikarubi/voluseg#3]
Hi Mika,

Just wanted to let you know that Python sends a warning for Line 157 of step4.py regarding how one indexes bvolume_mean.value:

`FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use 'arr[tuple(seq)]' instead of 'arr[seq]'. In the future this will be interpreted as an array index, 'arr[np.array(seq)]', which will result either in an error or a different result.`

Best,
Javier

**Comment by mikarubi** [comment]
fixed.
