### ISSUE TITLE
Volume dimensions order

### ISSUE THREAD

**Issue by luiztauffer** [mikarubi/voluseg#37]
The current code seems to presume a specific order of dimensions `(z, y, x)` for the input volumes:

https://github.com/mikarubi/voluseg/blob/3b8465d710815eac7733d681880a67eef891bc73/voluseg/_steps/step1.py#L59

But data coming from other sources might have a different order. For example, in NWB the order of dimensions should be `(t, x, y)` or `(t, x, y, z)`, [see here](https://pynwb.readthedocs.io/en/stable/pynwb.ophys.html#pynwb.ophys.TwoPhotonSeries).

One idea is to have a parameters string argument `dimensions_order` which would:
- have a default value of `z,y,x`, as it is presumed today
- enforce the NWB order `x,y,z` if `ext==".nwb"`

any other suggestion, @mikarubi ?

**Comment by mikarubi** [comment]
Agree, let's call it `dim_order` to parallel `dir_input`, etc. My suggestion is also to have an `"auto"` option for this parameter. When `"auto"` is chosen by the user, voluseg attempts to order the volume in such a way that the first dimension has the most voxels, followed by the second, followed by the third.
